[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/library.js"
  to = "/.netlify/functions/library"
  status = 200

[[redirects]]
  from = "/preview"
  to = "/.netlify/functions/preview"
  status = 200

[[redirects]]
  from = "/payment"
  to = "/.netlify/functions/payment"
  status = 200
