[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/SS_Klarna3.js"
  to = "/.netlify/functions/SS_Klarna3"
  status = 200

[[redirects]]
  from = "/SS_TEST.js"
  to = "/.netlify/functions/SS_TEST"
  status = 200

[[redirects]]
  from = "/preview"
  to = "/.netlify/functions/preview"
  status = 200

[[redirects]]
  from = "/payment"
  to = "/.netlify/functions/payment"
  status = 200
